# Generated by Django 4.0.5 on 2022-06-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creacion', models.DateTimeField(auto_now_add=True)),
                ('Actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
