# Generated by Django 4.0.5 on 2022-06-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['-Creacion'], 'verbose_name': 'Cursos', 'verbose_name_plural': 'Cursos'},
        ),
    ]
