# Generated by Django 4.0.5 on 2022-06-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['-creacion'], 'verbose_name': 'Cursos', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='Actualizacion',
            new_name='actualizacion',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='Creacion',
            new_name='creacion',
        ),
    ]
