# Generated by Django 4.0.5 on 2022-06-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_cursos_options_remove_cursos_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name': 'Cursos', 'verbose_name_plural': 'Cursos'},
        ),
    ]
