# Generated by Django 4.0.5 on 2022-06-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_cursos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='creador',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='descripcion',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='nombre',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='precio',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='requisitos',
            field=models.TextField(default=True),
        ),
    ]
