# Generated by Django 4.0.5 on 2022-07-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_cursos_imagen_alter_cursos_creador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoComentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Llave')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('Creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Creador')),
            ],
        ),
    ]
