# Generated by Django 4.0.5 on 2022-07-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_cursocomentario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursocomentario',
            name='coment',
            field=models.TextField(default=False, verbose_name='Comentarios'),
        ),
    ]
