# Generated by Django 4.0.5 on 2022-07-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_cursocomentario_coment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursocomentario',
            old_name='Creador',
            new_name='creador',
        ),
    ]
