# Generated by Django 4.0.5 on 2022-07-01 13:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_rename_creador_cursocomentario_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursocomentario',
            name='coment',
            field=ckeditor.fields.RichTextField(default=False, verbose_name='Comentarios'),
        ),
    ]
