# Generated by Django 4.0.5 on 2022-08-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_alter_cursocomentario_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='creador',
            field=models.CharField(max_length=50, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='precio',
            field=models.CharField(max_length=50, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='requisitos',
            field=models.TextField(verbose_name='Requisitos'),
        ),
    ]
