# Generated by Django 4.0.5 on 2022-08-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_comentariocontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariocontacto',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Actualizacion'),
        ),
    ]
