# Generated by Django 4.0.5 on 2022-08-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_alter_comentariocontacto_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('descripcion', models.TimeField(verbose_name='Descripcion')),
                ('archivo', models.FileField(upload_to='archivos', verbose_name='Archivo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Actualizacion')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-created'],
            },
        ),
    ]
