# Generated by Django 4.0.5 on 2022-08-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Creacion'),
        ),
    ]
